OT169-40: Get names from all categories
alkemyTech/OT169-Java-server pull request #35
Opened 2022-03-28 21:52 UTC by FrancoFelg

This PR adds:

> CategoryDTO
> CategoriesController
> CategoryService
> Endpoint: GetNamesFromAll

2022-03-28 22:10 UTC, her-o requested changes

2022-03-28 22:10 UTC, her-o commented on src/main/java/com/alkemy/ong/controller/CategoriesController.java
> +	private CategoryRepository categoryRepository;
El repositorio no se está usando dentro de esta clase, se podría dejar la dependencia directamente dentro del service

2022-03-29 14:31 UTC, npistone commented
El conflicto de la rama es que se agregan las anotaciones  de la creación de la entidad.

2022-03-29 21:12 UTC, her-o approved these changes

2022-03-29 21:31 UTC, juan1977lopez approved these changes
Aprobado

2022-03-29 21:31 UTC, merged